name: alphatwirl-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - pandas
  - root
  - pip:
    - alphatwirl>=0.21.2
    - qtwirl>=0.07.0
    - git+https://github.com/alphatwirl/scribblers
